### ISSUE TITLE
Customers doesn't return all customers

### ISSUE THREAD

**Issue by basiltap** [woocommerce/wc-api-php#309] opened 2021-10-21 14:44 UTC
Hi,
  I'm trying to retrieve all the customers from woocommerce api, although I try it with per_page=100 and different pages, it will only retrieve customers in the first 3 pages, although the number of customers is almost 3900.
From the wordpress woocommerce dashboard I can see the 39 pages with 100 customers per page, but not from the api call.

My call is: `https://myweb.com/wp-json/wc/v3/customers?per_page=100&page=30` 

When page is greater thant 3, it always return an empty array.

What am I doing wrong?

**Comment by claudiosanches** [comment] 2022-03-16 20:53
Hello @basiltap,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report [wc-api-php](https://github.com/woocommerce/wc-api-php) bugs only.

For issues with the WooCommerce REST API, please try the WP forum: https://wordpress.org/support/plugin/woocommerce/

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed by claudiosanches** 2022-03-16 20:53 UTC
