### ISSUE TITLE
post/put orders

### ISSUE THREAD

**Issue by johnwrise** [woocommerce/wc-api-php#108] opened 2017-04-26 02:23 UTC
as subject post/put using below array:

        $data = array (
            'status' => 'completed',
            'set_paid' => 'true'
        );

Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in \woocommerce-api\wc-api-php-1.2.0\src\WooCommerce\HttpClient\HttpClient.php on line 340

follow:
http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order
$data = [
    'status' => 'completed'
];

and

http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order
'set_paid' => true

Please help, thanks

**Comment by claudiosanches** [comment] 2017-04-26 19:29
Note that the fatal error it's because you are not catching the exception like in the example: https://github.com/woocommerce/wc-api-php#response

But still this is caused by the response from your WooCommerce installation that is sending a invalid JSON, that's why you are getting the response 'Syntax error'.

Again I'm closing it, since this is not an issue with this REST API wrapper, and if you need support with WooCommerce REST API or WordPress you can use: https://wordpress.org/support/plugin/woocommerce
Thanks.

**Closed by claudiosanches** 2017-04-26 19:29 UTC
