### ISSUE TITLE
Getting Syntax error

### ISSUE THREAD

**Issue by tundak** [woocommerce/wc-api-php#99] opened 2017-03-30 21:28 UTC
Hi,
i have developed a plugin using API for woocommerce. I have setup plugin at 2 server.
1. godaddy shared hosting
2. My VPS server

with my VPS everything fine but with same code it giving Syntax error at godaddy server.

**Error Log:**
```
Syntax errorAutomattic\WooCommerce\HttpClient\Response Object
(
    [code:Automattic\WooCommerce\HttpClient\Response:private] => 200
    [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array
        (
            [Date] => Thu, 30 Mar 2017 21:16:04 GMT
            [Server] => Apache
            [Expires] => Wed, 11 Jan 1984 05:00:00 GMT
            [Cache-Control] => no-cache, must-revalidate, max-age=0
            [Link] => <http://f40.929.myftpupload.com/?rest_route=/>; rel="https://api.w.org/", <http://f40.929.myftpupload.com/>; rel=shortlink
            [Set-Cookie] => yith_wcwl_products=%5B%5D; expires=Thu, 30-Mar-2017 20:16:05 GMT; Max-Age=-3600; path=/
            [Vary] => Accept-Encoding
            [Transfer-Encoding] => chunked
            [Content-Type] => text/html; charset=UTF-8
            [X-Port] => port_10505
        )

    [body:Automattic\WooCommerce\HttpClient\Response:private] =>
```

**Request Param**
```php
			foreach ($listpro as $var) {
				$order_colorID 	=$var['color']['id'];
			  	$colorName 	=$var['color']['name'];
			  	$order_sizeID 	=$var['size']['id'];
			  	$sizeName 	=$var['size']['name'];
			  	$pimage	=    $var['image'];
				$price= $var['prices'][1];			  		  

				$varsku = $order_item_id.'_'.$order_product_id.'_'.$order_colorID.'_'.$order_sizeID;

				            $varinats2[]=[
				            				'sku'=>$varsku,
								            'regular_price' => $price,
								            'image' => [
								                [
								                    'src' => $pimage,
								                    'position' => 0
								                ]
								            ],
								            'attributes' => [
								                [
								                    'name' => 'Color',
								                    'option' => $colorName
								                ],
								                [
								                    'name' => 'Size',
								                    'option' => $sizeName
								                ]
								            ]
								        ];
				   $imgposition++;	
			}
			
			// implement woocommerce API for add product
				$woocommerce = new Client(
				    get_home_url(), 
				    get_option('wc_gy_custom_tabs_api2'), 
				    get_option('wc_gy_custom_tabs_api3'),
				    [
				        'wp_api' => true,
				        'version' => 'wc/v1',
				    ]
				);	

			//product data
				$data = [
				    'name' => $name,
				    'type' => 'variable',
				    'description' => $description,
				    'short_description' => $description,
				    "sku"=> $order_item_id,
				    'images' => [
				        [
				            'src' => $pimage,
				            'position' => 0
				        ],
				    ],
				    'attributes' => [
				        [
				            'name' => 'Color',
				            'position' => 0,
				            'visible' => true,
				            'variation' => true,
				            'options' => $colors
				        ],
				        [
				            'name' => 'Size',
				            'position' => 0,
				            'visible' => true,
				            'variation' => true,
				            'options' => $sizes
				        ]
				    ],
				    'variations' => $varinats2
				];


					try {
					    // Array of response results.
					    $results = $woocommerce->post('products', $data);
					    // Last request data.
					    $lastRequest = $woocommerce->http->getRequest();
					    $lastRequest->getUrl(); // Requested URL (string).
					    $lastRequest->getMethod(); // Request method (string).
					    $lastRequest->getParameters(); // Request parameters (array).
					    $lastRequest->getHeaders(); // Request headers (array).
					    $lastRequest->getBody(); // Request body (JSON).

					    // Last response data.
					    $lastResponse = $woocommerce->http->getResponse();
					    $lastResponse->getCode(); // Response code (int).
					    $lastResponse->getHeaders(); // Response headers (array).
					    $lastResponse->getBody(); // Response body (JSON).

					} catch (HttpClientException $e) {
					    $e->getMessage(); // Error message.
					    //$e->getRequest(); // Last request data.
					    $e->getResponse(); // Last response data.
					    print_r($e->getMessage());
					    print_r($e->getResponse());
					    print_r($e->getMessage());
					}
```

**Comment by claudiosanches** [comment] 2017-03-31 04:45
Well, just printing "Syntax error"?
Do sounds like an issue with this REST API lib.
Maybe it's returning an invalid JSON from our server due PHP errors caused by your theme or plugins.
Still not an issue with this lib, that's why I'm closing.

**Closed by claudiosanches** 2017-03-31 04:45 UTC

**Comment by tundak** [comment] 2017-03-31 16:15
i have disabled all plugins and switch to default theme but still same issue

Syntax errorAutomattic\WooCommerce\HttpClient\Response Object
(
    [code:Automattic\WooCommerce\HttpClient\Response:private] => 200
    [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array
        (
            [Date] => Fri, 31 Mar 2017 16:11:27 GMT
            [Server] => Apache
            [Expires] => Wed, 11 Jan 1984 05:00:00 GMT
            [Cache-Control] => no-cache, must-revalidate, max-age=0
            [Link] => <http://f40.929.myftpupload.com/?rest_route=/>; rel="https://api.w.org/", <http://f40.929.myftpupload.com/>; rel=shortlink
            [Vary] => Accept-Encoding
            [Transfer-Encoding] => chunked
            [Content-Type] => text/html; charset=UTF-8
            [X-Port] => port_10505
        )

    [body:Automattic\WooCommerce\HttpClient\Response:private] =>

**Comment by claudiosanches** [comment] 2017-03-31 17:53
Still this is the response and you are not handing properly PHP exceptions.
There is nothing related to this library.
