### ISSUE TITLE
Empty error response validation

### ISSUE THREAD

**Issue by kristapsPrintful** [woocommerce/wc-api-php#228] opened 2018-11-08 09:31 UTC
https://github.com/woocommerce/wc-api-php/blob/c10712860866d6885d2be00835ad88204896d69b/src/WooCommerce/HttpClient/HttpClient.php#L344

There's an issue in lookForErrors function in HttpClient.php. There are various cases where POST method returns error, but the body is empty, therefore parsedResponse actually has nothing in it which is not validated. Typical errors `Syntax error`, `Execution time-out`.
Exception thrown because of empty parsedResponse property:
`Trying to get property of non-object in automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:344`. 

Example case when this happens: posting product images in batch [method: **products/batch**] possibly other as well

**Comment by claudiosanches** [comment] 2019-01-16 18:37
Please show me a code example.

**Comment by kristapsPrintful** [comment] 2019-01-17 09:09
I was unable to create a request that triggers such case 100% of the time. Issue might be related to used plugins corrupting data or server configuration, but that's just a guess.
The thing is that `$errors` can be array or object, but in some cases it is empty.
e.g. response I am receiving containing error:
`{
errors: [], 
parsedResponse: []
}`
Therefore `is_array($errors)` is true, yet `$errorMessage = $errors[0]->message` is inaccessible.

**Comment by claudiosanches** [comment] 2019-01-17 18:06
@kristapsPrintful so this should help for now: https://github.com/woocommerce/wc-api-php/commit/6c52acbbc25f0d808257d2ec86b22689869a32ab

I'll close this issue, since there is no steps to reproduce, but please, let me know if the problem still persist.

**Closed by claudiosanches** 2019-01-17 18:06 UTC

**Comment by e-hop** [comment] 2020-10-28 05:38
+1 In my case it happens when i use put. It updates the order, but generates this error
![image](https://user-images.githubusercontent.com/62304175/97396820-75d16c80-18ad-11eb-8cd7-6560a90e4a43.png)
