### ISSUE TITLE
JSON ERROR: Syntax error

### ISSUE THREAD

**Issue by jlavnv** [woocommerce/wc-api-php#291] opened 2020-11-17 18:13 UTC
I get a "JSON ERROR: Syntax error" error when trying to mount using **$woocommerce->get('order').**
It can't be dynamic and I've found that **per_page <10** must be accessed for it to work.
Do not know if this is an error or not?
With **$woocommerce->get()** it still works fine for **customers** or **products**.
There is no way to get all available orders.

**Comment by stefaner1** [comment] 2020-11-24 09:52
After updating woocommerce I got the same problem.

**Comment by rogerad** [comment] 2020-11-24 12:31
**This works** 


$website1 = 'https://store1.woomultistock.com';
--------------------------------------------------------
**This does not work**

$website1 = 'https://www.store1.woomultistock.com';
---------------------------------------------------

**This works on full domain name**

 $website1 = 'https://www.store1rog.xyz';

-----------------------------------------------------

I SPENT DAYS TRYING TO FIX IT 
MAKE SURE PERMALINKS ARE CORRECT

**Comment by stefaner1** [comment] 2020-11-24 15:18
FIX!
WP Hide need to have disabled wp-api blocking.

**Comment by filoor** [comment] 2020-12-15 13:02
Any fix for this issue i have changed my url but still  Syntax error like @rogerad recommended but still nothing.

**Comment by willie-lee** [comment] 2020-12-18 00:23
no longer support for this package?

**Comment by ashwin-kain** [comment] 2021-01-01 20:02
I'm also getting the same error. any solution??

**Comment by claudiosanches** [comment] 2021-03-17 16:42
This kind of error generally is triggered by a website throwing PHP warnings and errors together with the REST API response, generally gets fixed by fixing those errors or disabling `WP_DEBUG` and PHP error display.

**Comment by claudiosanches** [comment] 2021-03-17 16:43
Please note that "Syntax error" comes from the website receiving your requests.

**Comment by polsola** [comment] 2021-03-30 17:20
Hello! I'm facing the same issue, the thing is when I try it on my local environment it works great but when pulling the api from the server I was getting the **Syntax Error**

Adding some debug to the curl request I finally found that I'm getting a "**415 Unsupported Media Type**" response, I've checked and I have the same PHP version on both so currently I have no clue of what is happening, I'll try some more options

Any help would be appreciated thanks!

**Comment by claudiosanches** [comment] 2021-03-30 17:28
Hello @polsola, this issue is from your external server, you need to fix it there.

I'm closing this issue since there's no steps to reproduce with this library and it's related to your web servers.

**Closed by claudiosanches** 2021-03-30 17:28 UTC

**Comment by oceceli** [comment] 2023-03-05 20:36
Hello, I had the same issue with REST API. 
Settings -> Permalinks -> Post Name
I've changed like this and it just worked. I think it should not stay on the "plain" option.

**Comment by osloucosgritamhow** [comment] 2023-10-17 18:07
CloudFlare WAF Blocking the api, disable it!
