### ISSUE TITLE
PHP client converts header index keys to lowercase

### ISSUE THREAD

**Issue by ghost** [woocommerce/wc-api-php#249] opened 2019-10-28 19:11 UTC
When using the PHP client, v3.0.0, a call to getHeaders() will return the headers, but with array indexes in lowercase:

```
2019-10-28 18:39:01 Info: WC Headers: Array
(
    [date] => Mon, 28 Oct 2019 18:38:59 GMT
    [server] => Apache
    [x-robots-tag] => noindex
    [x-content-type-options] => nosniff
    [access-control-expose-headers] => X-WP-Total, X-WP-TotalPages
    [access-control-allow-headers] => Authorization, Content-Type
    [expires] => Wed, 11 Jan 1984 05:00:00 GMT
    [cache-control] => no-transform, no-cache, must-revalidate, max-age=0
    [x-wp-total] => 222
    [x-wp-totalpages] => 23
    [link] => <xxx my API link xxx>; rel="next"
    [allow] => GET, POST
    [set-cookie] => wfwaf-authcookie-xxxcookiesetbyWordFence?xxx; expires=Tue, 29-Oct-2019 06:39:00 GMT; Max-Age=43200; path=/; secure; HttpOnly
    [vary] => User-Agent
    [content-type] => application/json; charset=UTF-8
)
```

Via Postman for instance, you can see that the header keys are not lowercase.

I noticed this when I started getting warnings that keys 'X-WP-Total' and 'X-WP-TotalPages' don't exist.

**Comment by LocalHeroPro** [comment] 2020-02-25 17:48
The same issue in my case.
When running code in Cent OS 7, I get as mentioned in documentation right here https://woocommerce.github.io/woocommerce-rest-api-docs/#pagination, that we can get some data from `X-WP-Total and X-WP-TotalPages`, but on Windows with Xampp I get strlowercase on headers ;/
```php
$this->client->get($endpoint, $parameters);
$headers = $this->client->http->getResponse()->getHeaders();
```
Please fix it.

**Comment by harshdeeply** [comment] 2021-08-31 21:38
Just wondering if there was a workaround/fix was made available for this @LocalHeroPro.

**Comment by LocalHeroPro** [comment] 2021-08-31 22:21
```php
$value = (int)($headers['X-WP-Total'] ?? $headers['x-wp-total']);
// or
$headers = array_change_key_case($headers);
```
All depends on your needs.

**Comment by claudiosanches** [comment] 2022-03-18 21:09
Hi,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end.

I'm using WooCommerce 6.3.0 and WP 5.9.2 with the latest version of this library, all results return as expected:

```
Array
(
    [Date] => Fri, 18 Mar 2022 21:06:03 GMT
    [Server] => Apache/2.4.41 (Ubuntu)
    [X-Robots-Tag] => noindex
    [Link] => <http://woo.local/wp-json/wc/v3/products?_fields%5B0%5D=id&_fields%5B1%5D=price&oauth_consumer_key=ck_912cb0a0893fd55751253d808f07cc934925d0d0&oauth_nonce=1784a5eca41cf4f1f212a7e366e5d99ec0008120&oauth_signature=sy0Eb2oW1UClxwzi5Hh964Vjzu40PzoIDRbKwJnU9tg&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1647637563&page=2>; rel="next"
    [X-Content-Type-Options] => nosniff
    [Access-Control-Expose-Headers] => X-WP-Total, X-WP-TotalPages, Link
    [Access-Control-Allow-Headers] => Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
    [Expires] => Wed, 11 Jan 1984 05:00:00 GMT
    [Cache-Control] => no-cache, must-revalidate, max-age=0
    [X-WP-Total] => 32
    [X-WP-TotalPages] => 4
    [Allow] => GET, POST
    [Content-Length] => 229
    [Content-Type] => application/json; charset=UTF-8
)
```

Also note that this library doesn't change this keys or try convert to lowercase.
I'm closing since it doesn't seems an issue on this library.
If you are still facing this issue please provide us with more details about the issue which may help us to evaluate it further and reopen this issue.

**Closed by claudiosanches** 2022-03-18 21:09 UTC
